* 文档结构
** 标题
    标题定义了大纲树的结构. Org的标题以一个或多个星号开头
   #+BEGIN_SRC org
     ,*   Top level headline
     ,**  Second level
     ,*** 3rd level
     ,    some text
     ,*** 3rd level
     ,    more text

     ,*   Another top level headline
   #+END_SRC
   
   * C-enter 可以创建一个标题

** 显示和隐藏的切换
   * <TAB> (org-cycle) :: 子树循环：以下面的循环状态来切换当前子树的状态
  #+BEGIN_EXAMPLE
	,-> FOLDED -> CHILDREN -> SUBTREE --.
	'-----------------------------------'
	#+END_EXAMPLE

   * S-<TAB> / C-u <TAB> (org-global-cycle) :: 全局循环:使整个缓存区在在不同状态间切换
  #+BEGIN_EXAMPLE
	 ,-> OVERVIEW -> CONTENTS -> SHOW ALL --.
	'--------------------------------------'
	#+END_EXAMPLE
  若再S-<TAB>前加了一个数字前缀N,那么CPMTEMTS一直到第N个层次的内容都会显示出来.
  需要注意的是,若是在编辑表格中,S-<TAB>的作用是跳到上一个域.

   * C-u C-u <TAB> (show-all) :: 
	显示所有信息,包括'抽屉'内的信息

   * C-c C-r (org-reveal) :: 
	显示光标周围的上下文,也就是显示当前条目,以及所有上层标题. 

   * C-c C-k (show-branches) :: 
	展开所有子树的标题,如果只有一个子树,那么内容也显示出来.
  (隐藏当前子树？)

   * C-c C-x b (org-tree-to-indirect-buffer) :: 
	把当前子树显示在indirect buffer(新的buffer中)中. 
  如果加了一个前缀参数N,它会向下进入地N层子树并在indirect buffer中显示该子树. 
  如果N是负数,那么就是向上进入N层的父节点. 
  如果命令执行前加了C-u前缀,则打开新的indirect buffer,而不会关闭之前打开的indirect buffer.
  
   * C-c C-x v (org-copy-visible) :: 
	拷贝文本块中的可见文本到kill ring中
  
  当Emacs第一次打开一个Org文件时,全局状态为OVERVIEW,也就是说,只有顶层的标题是可见的. 
  这个行为可以通过配置'org-startup-folded'变量来改变.
  或者可以在文件的任何地方添加下面所列出的任何一句,Emacs就会根据这句配置信息自动设置初始的状态.
   #+BEGIN_SRC org
     ,#+STARTUP: overview
     ,#+STARTUP: content
     ,#+STARTUP: showall
     ,#+STARTUP: showeverything
   #+END_SRC

   此外,任何带有'VISIBILITY'属性名的条目(参考[[#Properities and columns][属性与列]])会相应地按照该属性值来设置可见性. 
  该属性的有效值可以使'folded','children','cotent'和'all'
  
   * C-u C-u <TAB> (org-set-startup-visiblity) ::
  重置该buffer的可见性为该buffer在启动时的可见性,
  也就是说根据buffer的'startup'选项和各个单独条目的'VISIBILITY'属性来重新设置整个buffer的可见性.
  
** 移动
 * C-c C-p (outline-previous-visible-heading) :: 
	上一个标题
 * C-c C-n (outline-next-visible-heading) ::
  下一个标题
   
 * C-c C-b (org-backward-same-level) :: 
	同一级的上一个标题 
 * C-c C-f (org-forward-same-level) :: 
	同一级的下一个标题

 * C-c C-u (outline-up-heading) :: 
	回到上一级标题
  
 * C-c C-j (org-goto) :: 
	跳转到其他位置的同时不改变当前大纲的可见性. 
  在一个临时buffer中显示文档的结构,在这个临时buffer中你可以使用下面的快捷键来定位:
	#+BEGIN_EXAMPLE
	<TAB>           切换可见性
	<down> / <up>   下一个/上一个可见的标题
	<RET>           选定当前位置
	/               在树中作一个匹配查询
	如果你关掉了org-goto-auto-isearch选项,下面这些快捷键才可用
	n / p           下一个/上一个可见的标题
	f / b           同级别的上一个/下一个标题
	u               回到上一级标题
	0-9             数字参数
	q               退出这个临时buffer
	#+END_EXAMPLE
	参见变量'org-goto-interface'
  
** 结构编辑
 * M-<RET> (org-insert-heading) ::
  插入一个与当前位置同级别的新标题. 如果光标位于一个普通的列表项,新的列表项被创建(参见[[#Plain list][普通列表]]). 
  要强制创建新标题,则需要使用前缀参数. 
  如果在一行的中间执行这个命令,那么这一行会被分割成两行,光标到行尾的内容会成为新的标题. 
  如果实在一个标题的开头执行这个命令,那么新标题会天骄到当前行的前面. 
  如果是在所有行的前面执行这个命令,那么就创建了一个新的文件头. [fn:nnandnw]
  如果是在折叠起来的子树末尾使用这个命令(也就是说,是在标题末尾的省略号之后),那么与当前标题类似的标题会被插入到这个子树的末尾.

 * C-<RET> (org-insert-heading-respect-content) :: 
	类似与M-<RET>,不同之处在于,当在当前标题后增加一个新标题时,
  M-<RET>会在当前标题的内容前增加一个新标题(内容成为这个新标题的内容),
  而C-<ERT>则在内容后增加一个新标题(内容还是原标题的内容). 
  这个命令在条目的任何地方都是一样的行为.
** 注脚
  下面列举几种有效的注脚引用:
   * [ 1 ] ::
      一个纯数字的注脚标记. 与'footnote.el'兼容,但是不推荐使用,因为像'[ 1 ]'这样的东西,很可能是code snippet的一部分.
   * [ fn:name ] :: 
      一个带有名字的注脚引用,这里name是一个唯一的标签.如果是自动创建的注脚引用的化,则会是一个数字.
   * [ fn:: This is the inline definitiion of this footnote ] :: 
      这是一个类似LaTeX的匿名注脚,其中注脚的定义直接放在引用的位置.
   * [ fn:name:a definition ] ::
      这是一个带有名字的自定义的注脚. 由于Org-mode允许从多处引用到同一个说明,你可以使用[ fn:name ]来创建更多的引用.
      
   注脚标记可以被自动创建,你也可以自定义标记自动创建时的名字. 
   这是由变量'org-footnote-auto-label'变量和变量相应的'#+STARTUP'关键字来决定的. 
   欲了解详情请查看该变量的文档字符串.

   * C-c C-c :: 
   当光标位于注脚[引用处]时,跳转到注脚[定义处]. 
   若光标处于注脚[定义处],则跳转回注脚[引用处]. 
   若在标注位置上用带前置参数的方式调用该命令，则弹出一个与C-c C-x f一样的菜单.

   * C-c C-o 或 鼠标左键 或鼠标右键 :: 
   注脚标签也是注脚[定义]与注脚[引用]相互之间的一种链接，你可以使用跳转链接的一般命令来在注脚定义/引用间相互跳转.

   * C-c C-x f ::
     注脚行为命令
     * 当光标位于注脚引用处，该命令会跳转到注脚定义处，若光标处于注脚定义处，跳转到(第一个)引用处。
       否则，会创建一个新的注脚.
     * 当光标处于文本中时，会创建一个新的注脚
     * 当使用带前置参数的方式调用该命令, 会显示出一个附加选项菜单供你选择:
     #+BEGIN_EXAMPLE
       s   以引用顺序为依据对注脚的定义进行排序. 在编辑过程中,Org不会对注脚的定义进行排序操作. 
       如果你向对这些注脚的定义进行排序,使用这个命令,在对注脚定义进行排序的同时,也会根据'org-footnote-section'来移动整个条目. 
       用户可以通过配置变量'org-footnote-auto-adjust'来实现在每次插入/删除一个注脚后自动对注脚定义进行重新排序.
       r   对类型fn:N这样的以简单数字命名的注脚进行重新编号. 
       可以通过配置变量'org-footnote-auto-adjust'来实现每次插入/删除一个标注就自动对标注进行重新编号.
       S   先执行r操作,然后执行s操作
       n   标准化所有的标准,方法为先收集所有的标注定义(包括自定义的标注定义)并移动到一个特定的区域中,然后按顺序对这些定义进行编号. 
       那些标注引用随后也会转换为相应的数字. 这常常是在完成一篇文档前的最后一个步骤(例如,要发送email时). 
       在导出文档时,exporter会自动做这一步.或者当触发类似message-send-hook时,类似的动作也会自动触发.
       d   删除当前位置的标注,连同所有的标注定义和标注引用
     #+END_EXAMPLE

* Footnotes

[fn:nnandnw]
